Repository OCA/server-env, pull requests merged in 2020-04, with the labels that each got.

#45 server_environment: running_env default to `test` (fix #44)
  .travis.yml
  server_environment/readme/CONFIGURE.rst
  server_environment/server_env.py
  server_environment/tests/common.py
  server_environment/tests/test_environment_variable.py
  server_environment/tests/test_server_environment.py
Labels: approved, needs fixing, needs review

#34 [12.0][FIX][carrier_environment] remove name from server env fields
  carrier_environment/models/carrier_account.py
Labels: approved, bot is merging ⏳, ready to merge

#46 [11.0][FIX] server_environment: running_env default to `test`
  .travis.yml
  server_environment/readme/CONFIGURE.rst
  server_environment/serv_config.py
  server_environment/tests/common.py
  server_environment/tests/test_environment_variable.py
  server_environment/tests/test_server_environment.py
  server_environment_files_sample/test/base.conf
  server_environment_files_sample/test/mytopic.conf
Labels: approved, bot is merging ⏳

#47 [12.0][FIX] server_environment: running_env default to `test`
  .travis.yml
  server_environment/readme/CONFIGURE.rst
  server_environment/serv_config.py
  server_environment/tests/common.py
  server_environment/tests/test_environment_variable.py
  server_environment/tests/test_server_environment.py
  server_environment_files_sample/test/base.conf
  server_environment_files_sample/test/mytopic.conf
  server_environment_files_sample/test/pos_environment.conf
Labels: approved, bot is merging ⏳

#35 [12.0] Store the 'server.config' fields in sparse fields
  server_environment/serv_config.py
Labels: approved, bot is merging ⏳, ready to merge
