Repository OCA/server-env, pull requests merged in 2020-03, with the labels that each got.

#40 [13.0] [FIX] mail_environment: fix server_type field
  mail_environment/models/fetchmail_server.py
Labels: approved

#3 [11.0][Add] Module auth_oauth_environment
  auth_oauth_environment/README.rst
  auth_oauth_environment/__init__.py
  auth_oauth_environment/__manifest__.py
  auth_oauth_environment/models/__init__.py
  auth_oauth_environment/models/auth_oauth_provider.py
  auth_oauth_environment/models/res_config_settings.py
  auth_oauth_environment/views/auth_oauth_provider.xml
Labels: approved

#23 [12.0] Add new module data_encryption
  data_encryption/__init__.py
  data_encryption/__manifest__.py
  data_encryption/models/__init__.py
  data_encryption/models/encrypted_data.py
  data_encryption/readme/CONFIGURE.rst
  data_encryption/readme/CONTRIBUTORS.rst
  data_encryption/readme/DESCRIPTION.rst
  data_encryption/readme/ROADMAP.rst
  data_encryption/security/ir.model.access.csv
  data_encryption/tests/__init__.py
  data_encryption/tests/common.py
  data_encryption/tests/test_data_encrypt.py
Labels: needs review

#24 [12.0] Add module server_environment_data_encryption
  server_environment_data_encryption/__init__.py
  server_environment_data_encryption/__manifest__.py
  server_environment_data_encryption/models/__init__.py
  server_environment_data_encryption/models/server_env_mixin.py
  server_environment_data_encryption/readme/CONFIGURE.rst
  server_environment_data_encryption/readme/CONTRIBUTORS.rst
  server_environment_data_encryption/readme/DESCRIPTION.rst
  server_environment_data_encryption/tests/__init__.py
  server_environment_data_encryption/tests/fixtures/base.xml
  server_environment_data_encryption/tests/fixtures/res1.xml
  server_environment_data_encryption/tests/fixtures/res2.xml
  server_environment_data_encryption/tests/test_server_environment_data_encrypt.py
Labels: approved, needs review, ready to merge
