Repository OCA/server-env, pull requests merged in 2022-10, with the labels that each got.

#99 [FIX] server_environment_ir_config_parameter
  server_environment_ir_config_parameter/models/ir_config_parameter.py
  server_environment_ir_config_parameter/tests/test_server_environment_ircp.py
Labels: approved, ready to merge, bot is merging ⏳

#118 FIX data_encryption: typo
  data_encryption/README.rst
Labels: approved, bot is merging ⏳

#125 [15.0][FW] [14.0][FW] server_environment_ir_config_parameter: Port PR from 12.0/13.0 to 14.0
  server_environment_ir_config_parameter/__manifest__.py
  server_environment_ir_config_parameter/models/ir_config_parameter.py
  server_environment_ir_config_parameter/readme/CONTRIBUTORS.rst
  server_environment_ir_config_parameter/views/view_ir_config_parameter.xml
Labels: bot is merging ⏳

#126 [15.0][FW] server_environment: multiple ports from 14.0
  server_environment/models/server_env_tech_name_mixin.py
Labels: bot is merging ⏳

#116 [14.0] [IMP] `server_environment`: don't print stack trace when the field can't be read
  server_environment/models/server_env_mixin.py
Labels: bug, approved, bot is merging ⏳

#129 [16.0][FW] [14.0] [IMP] `server_environment`: don't print stack trace when the field can't be read
  server_environment/models/server_env_mixin.py
Labels: bug, bot is merging ⏳

#128 [15.0][FW] [14.0] [IMP] `server_environment`: don't print stack trace when the field can't be read
  server_environment/models/server_env_mixin.py
Labels: bug, bot is merging ⏳

#123 [16.0][MIG] migration of data_encryption
  data_encryption/README.rst
  data_encryption/__init__.py
  data_encryption/__manifest__.py
  data_encryption/i18n/ca.po
  data_encryption/i18n/data_encryption.pot
  data_encryption/models/__init__.py
  data_encryption/models/encrypted_data.py
  data_encryption/readme/CONFIGURE.rst
  data_encryption/readme/CONTRIBUTORS.rst
  data_encryption/readme/DESCRIPTION.rst
  data_encryption/readme/ROADMAP.rst
  data_encryption/security/ir.model.access.csv
  data_encryption/static/description/icon.png
  data_encryption/static/description/index.html
  data_encryption/tests/__init__.py
  data_encryption/tests/common.py
  data_encryption/tests/test_data_encrypt.py
  requirements.txt
  setup/data_encryption/odoo/addons/data_encryption
  setup/data_encryption/setup.py
Labels: approved, migration, bot is merging ⏳
