Repository OCA/server-env, pull requests merged in 2023-04, with the labels that each got.

#153 [14.0] server_env: fix inverse method (closes #151)
  server_environment/models/server_env_mixin.py
Labels: bot is merging ⏳

#157 [MIG] auth_saml_environment: Migration to 15.0
  auth_saml_environment/README.rst
  auth_saml_environment/__init__.py
  auth_saml_environment/__manifest__.py
  auth_saml_environment/controllers/__init__.py
  auth_saml_environment/controllers/main.py
  auth_saml_environment/i18n/auth_saml_environment.pot
  auth_saml_environment/i18n/ca.po
  auth_saml_environment/models/__init__.py
  auth_saml_environment/models/auth_saml_provider.py
  auth_saml_environment/readme/CONFIGURE.rst
  auth_saml_environment/readme/CONTRIBUTORS.rst
  auth_saml_environment/readme/DESCRIPTION.rst
  auth_saml_environment/readme/INSTALL.rst
  auth_saml_environment/readme/ROADMAP.rst
  auth_saml_environment/readme/USAGE.rst
  auth_saml_environment/static/description/icon.png
  auth_saml_environment/static/description/index.html
  auth_saml_environment/tests/__init__.py
  auth_saml_environment/tests/test_environment_variable.py
  auth_saml_environment/views/saml_provider_view.xml
  setup/auth_saml_environment/odoo/addons/auth_saml_environment
  setup/auth_saml_environment/setup.py
Labels: approved, migration, bot is merging ⏳

#130 [MIG] server_environment_files_sample: Migration to 15.0
  server_environment_files_sample/README.rst
  server_environment_files_sample/__init__.py
  server_environment_files_sample/__manifest__.py
  server_environment_files_sample/default/base.conf
  server_environment_files_sample/default/mytopic.conf
  server_environment_files_sample/i18n/server_environment_files.pot
  server_environment_files_sample/i18n/server_environment_files_sample.pot
  server_environment_files_sample/preprod/mytopic.conf
  server_environment_files_sample/prod/base.conf
  server_environment_files_sample/prod/mytopic.conf
  server_environment_files_sample/readme/CONTRIBUTORS.rst
  server_environment_files_sample/readme/DESCRIPTION.rst
  server_environment_files_sample/readme/INSTALL.rst
  server_environment_files_sample/static/description/icon.png
  server_environment_files_sample/static/description/index.html
  server_environment_files_sample/test/base.conf
  server_environment_files_sample/test/mytopic.conf
  server_environment_files_sample/test/pos_environment.conf
  setup/server_environment_files_sample/odoo/addons/server_environment_files_sample
  setup/server_environment_files_sample/setup.py
Labels: approved, ready to merge, bot is merging ⏳
