Repository OCA/server-env, pull requests merged in 2025-04, with the labels that each got.

#224 [18][MIG] data_encryption
  data_encryption/README.rst
  data_encryption/__init__.py
  data_encryption/__manifest__.py
  data_encryption/i18n/ca.po
  data_encryption/i18n/data_encryption.pot
  data_encryption/i18n/de.po
  data_encryption/i18n/es.po
  data_encryption/i18n/it.po
  data_encryption/models/__init__.py
  data_encryption/models/encrypted_data.py
  data_encryption/pyproject.toml
  data_encryption/readme/CONFIGURE.md
  data_encryption/readme/CONTRIBUTORS.md
  data_encryption/readme/DESCRIPTION.md
  data_encryption/readme/ROADMAP.md
  data_encryption/security/ir.model.access.csv
  data_encryption/static/description/icon.png
  data_encryption/static/description/index.html
  data_encryption/tests/__init__.py
  data_encryption/tests/common.py
  data_encryption/tests/test_data_encrypt.py
  requirements.txt
Labels: approved, merged 🎉

#222 [18.0][FW PORT]server_environment: fix default method not passed
  server_environment/models/server_env_mixin.py
Labels: approved, bot is merging ⏳

#210 [18.0][IMP] server_environment: hide SMTP passwords
  server_environment/server_env.py
  server_environment/tests/common.py
  server_environment/tests/test_server_environment.py
  server_environment/tests/testfiles/testing/outmail.conf
Labels: approved, ready to merge, bot is merging ⏳

#226 [18][MIG] server_environment_data_encryption
  data_encryption/tests/common.py
  server_environment_data_encryption/README.rst
  server_environment_data_encryption/__init__.py
  server_environment_data_encryption/__manifest__.py
  server_environment_data_encryption/i18n/ca.po
  server_environment_data_encryption/i18n/es.po
  server_environment_data_encryption/i18n/it.po
  server_environment_data_encryption/i18n/server_environment_data_encryption.pot
  server_environment_data_encryption/models/__init__.py
  server_environment_data_encryption/models/server_env_mixin.py
  server_environment_data_encryption/pyproject.toml
  server_environment_data_encryption/readme/CONFIGURE.md
  server_environment_data_encryption/readme/CONTRIBUTORS.md
  server_environment_data_encryption/readme/DESCRIPTION.md
  server_environment_data_encryption/static/description/icon.png
  server_environment_data_encryption/static/description/index.html
  server_environment_data_encryption/tests/__init__.py
  server_environment_data_encryption/tests/fixtures/base.xml
  server_environment_data_encryption/tests/models.py
  server_environment_data_encryption/tests/test_server_environment_data_encrypt.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#228 [18.0][MIG] mail_environment_google_gmail: Migration to 18.0
  mail_environment_google_gmail/README.rst
  mail_environment_google_gmail/__init__.py
  mail_environment_google_gmail/__manifest__.py
  mail_environment_google_gmail/i18n/it.po
  mail_environment_google_gmail/i18n/mail_environment_google_gmail.pot
  mail_environment_google_gmail/models/__init__.py
  mail_environment_google_gmail/models/ir_mail_server.py
  mail_environment_google_gmail/pyproject.toml
  mail_environment_google_gmail/readme/CONFIGURE.md
  mail_environment_google_gmail/readme/CONTRIBUTORS.md
  mail_environment_google_gmail/readme/DESCRIPTION.md
  mail_environment_google_gmail/static/description/icon.png
  mail_environment_google_gmail/static/description/index.html
Labels: approved, merged 🎉
